CREATE TABLE Proyecto (
  Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
  Nombre NVARCHAR(100) NOT NULL,
  Descripcion NVARCHAR(MAX) NULL,
  FechaCreacion DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE Usuario (
  Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
  Nombre NVARCHAR(50) NOT NULL,
  Email NVARCHAR(256) NOT NULL,
  PasswordHash NVARCHAR(MAX) NOT NULL
);

CREATE TABLE Tarea (
  Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
  Titulo NVARCHAR(100) NOT NULL,
  Descripcion NVARCHAR(MAX) NULL,
  Estado INT NOT NULL,
  Prioridad INT NOT NULL,
  FechaVencimiento DATETIME2 NULL,
  FechaCreacion DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  ProyectoId UNIQUEIDENTIFIER NOT NULL
    CONSTRAINT FK_Tarea_Proyecto FOREIGN KEY REFERENCES Proyecto(Id),
  UsuarioAsignadoId UNIQUEIDENTIFIER NULL
    CONSTRAINT FK_Tarea_Usuario FOREIGN KEY REFERENCES Usuario(Id)
);
